name: Sync GH Pages

on:
  push:
    branches: [ main ]

jobs:
  image-lists:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate list of images
        run: |
          cd output
          mkdir -p file_lists
          find solar_scan/maps_solar-scan/solar-scan59_map_*.png -type f | jq -R . | jq -s . > file_lists/daily_quicklooks.json
          find fig/solarflux/callisto_meteoswiss_*.png -type f | jq -R . | jq -s . > file_lists/solar_raster.json
      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add --all output/file_lists
          git commit -m "Update images file lists" || echo "No changes to commit"
          git push
      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
